title: churrros' log
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://leejuhae.github.io/
paginate_path: 'blog/page:num/'
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: LeeJuhae
  email: leejuhae821@gmail.com

google_analytics: 'UA-58263416-1'
